"""
Hospital receptionist LLM agent powered by Ollama (local, no API key).
Manages multi-turn conversation and triggers appointment booking actions.
"""

import json
from datetime import date, datetime
from typing import Optional

import ollama
from loguru import logger

from config.settings import settings
from src.appointment.booking import (
    DOCTORS,
    BookingSystem,
    resolve_department,
)

# ── System prompt ──────────────────────────────────────────────────────────────

def _build_system_prompt() -> str:
    dept_list = ", ".join(d.title() for d in DOCTORS)
    today = date.today().strftime("%A, %B %d, %Y")
    tomorrow = (date.today() + __import__('datetime').timedelta(days=1)).strftime("%Y-%m-%d")

    return f"""### ROLE
You are {settings.receptionist_name}, a friendly and professional receptionist at {settings.hospital_name}.
Today: {today} | Tomorrow: {tomorrow}

### BEHAVIOR
1. **Persona**: Be warm and empathetic. If a patient is in pain, say "I'm sorry to hear that."
2. **Conversation**: Keep talk short (1-2 sentences). Ask for only ONE piece of information at a time.
3. **Data Extraction**: Extract name, phone, dept, doctor, date, and time from speech.
4. **Logic**: 
   - Mapping: Eye/Vision -> general, Heart/Chest -> cardiology, Bone/Joint -> orthopedic, Child/Baby -> pediatric, Women/Gynae -> gynecology, Brain/Neuro -> neurology.
   - Confirmation: ONLY book after summarizing all details and getting a "yes/confirmed" from the caller. 
   - "Thank you/Hello": Just greet back or acknowledge. Do NOT assume an appointment is being confirmed.

### OUTPUT FORMAT (JSON ONLY)
Reply with NO other text than this JSON:
{{
  "speech": "<warm words to say>",
  "action": "none | book_appointment | cancel_appointment | end_call",
  "data": {{
    "patient_name": "",
    "patient_phone": "",
    "department": "",
    "doctor_name": "",
    "appointment_date": "",
    "appointment_time": "",
    "reason": ""
  }}
}}
"""


# ── Agent class ────────────────────────────────────────────────────────────────

class HospitalAgent:
    def __init__(self):
        self.booking = BookingSystem()
        self._history: list = []
        self._collected: dict = {}

    # ── Public API ─────────────────────────────────────────────────────────────

    def reset(self):
        """Reset state for a new call."""
        self._history = []
        self._collected = {}

    async def get_greeting(self) -> str:
        result = await self._chat("A new caller has connected. Please greet them warmly.")
        return result.get("speech", f"Thank you for calling {settings.hospital_name}. This is {settings.receptionist_name}. How can I help you today?")

    async def process_turn(self, user_text: str) -> dict:
        """
        Process one user turn.
        Returns dict with 'speech', 'action', 'data'.
        May execute a booking/cancellation as a side effect.
        """
        result = await self._chat(user_text)

        # Merge collected data
        if result.get("data"):
            for k, v in result["data"].items():
                if v:
                    self._collected[k] = v

        action = result.get("action", "none")

        if action == "book_appointment":
            result = self._execute_booking(result)
        elif action == "cancel_appointment":
            result = self._execute_cancellation(result)

        return result

    async def process_turn_stream(self, user_text: str):
        """
        Yields strings (sentences) as they are generated by the LLM.
        The very last item yielded will be the complete response dict.
        """
        full_json_str = ""
        last_yielded_speech_idx = 0
        speech_buffer = ""
        
        import re
        
        async for content in self._chat_stream(user_text):
            full_json_str += content
            
            # Simple streaming extraction for "speech"
            # Look for: "speech": "
            # and then grab characters until the closing quote
            match = re.search(r'"speech"\s*:\s*"(.*?)"', full_json_str, re.DOTALL)
            if match:
                current_speech = match.group(1)
                new_symbols = current_speech[last_yielded_speech_idx:]
                
                if new_symbols:
                    speech_buffer += new_symbols
                    last_yielded_speech_idx += len(new_symbols)
                    
                    # Look for sentence boundaries in our buffer
                    # Split by . ! or ? followed by whitespace or end of string
                    sentences = re.split(r'(?<=[.!?])\s+', speech_buffer)
                    if len(sentences) > 1:
                        # Yield all complete sentences
                        for s in sentences[:-1]:
                            yield s
                        # Keep the last (potentially incomplete) one
                        speech_buffer = sentences[-1]

        # Final cleanup for the last sentence
        if speech_buffer.strip():
            yield speech_buffer.strip()

        # Parse final JSON to get result and update state
        try:
            result = json.loads(full_json_str)
        except:
            # Fallback regex if LLM output was slightly broken but speech was extracted
            match = re.search(r'"speech"\s*:\s*"(.*?)"', full_json_str, re.DOTALL)
            speech = match.group(1) if match else "I'm sorry, I'm having trouble thinking."
            result = {"speech": speech, "action": "none", "data": {}}

        # Process actions (bookings, history update)
        if result.get("data"):
            for k, v in result["data"].items():
                if v:
                    self._collected[k] = v
        self._normalise_collected()
        action = result.get("action", "none")
        if action == "book_appointment":
            result = self._execute_booking(result)
        elif action == "cancel_appointment":
            result = self._execute_cancellation(result)

        # Update history
        self._history.append({"role": "user", "content": user_text})
        self._history.append({"role": "assistant", "content": json.dumps(result)})
        if len(self._history) > 20:
            self._history = self._history[-20:]

        yield result

    # ── Normalisation ──────────────────────────────────────────────────────────

    def _normalise_collected(self):
        """
        Sanitise self._collected after each LLM turn.
        Handles time formats, department aliases, and date shortcuts.
        """
        import re as _re

        # ── Time normalisation ────────────────────────────────────────────────
        _TIME_MAP = {
            # hour → canonical slot (floor to nearest 30-min slot)
            (9, 0): "09:00 AM",  (9, 30): "09:30 AM",
            (10, 0): "10:00 AM", (10, 30): "10:30 AM",
            (11, 0): "11:00 AM", (11, 30): "11:30 AM",
            (14, 0): "02:00 PM", (14, 30): "02:30 PM",
            (15, 0): "03:00 PM", (15, 30): "03:30 PM",
            (16, 0): "04:00 PM", (16, 30): "04:30 PM",
        }
        _VALID_SLOTS = set(_TIME_MAP.values())

        raw_time = self._collected.get("appointment_time", "")
        if raw_time and raw_time not in _VALID_SLOTS:
            # Try to parse "2 pm", "14:00", "2:30 PM", "half past 2", etc.
            t = raw_time.lower().strip()
            hour, minute, meridiem = None, 0, None

            # "half past N" / "N thirty"
            half = _re.search(r'half\s+past\s+(\d+)|(\d+)\s+thirty', t)
            if half:
                h = int(half.group(1) or half.group(2))
                minute = 30
                hour = h

            if hour is None:
                m = _re.search(r'(\d{1,2})(?::(\d{2}))?\s*(am|pm)?', t)
                if m:
                    hour = int(m.group(1))
                    minute = int(m.group(2) or 0)
                    meridiem = m.group(3)

            if hour is not None:
                if meridiem == "pm" and hour < 12:
                    hour += 12
                elif meridiem == "am" and hour == 12:
                    hour = 0
                elif meridiem is None and hour <= 6:
                    hour += 12   # assume afternoon for "2", "3" etc

                # Snap minute to 0 or 30
                minute = 30 if minute >= 15 else 0
                canonical = _TIME_MAP.get((hour, minute))
                if canonical:
                    self._collected["appointment_time"] = canonical
                    logger.debug(f"[Agent] Time normalised: '{raw_time}' → '{canonical}'")
                else:
                    logger.warning(f"[Agent] Time '{raw_time}' could not map to a slot")

        # ── Department normalisation ─────────────────────────────────────────
        from src.appointment.booking import resolve_department
        raw_dept = self._collected.get("department", "")
        if raw_dept:
            resolved = resolve_department(raw_dept)
            if resolved:
                self._collected["department"] = resolved

        # ── Date normalisation ───────────────────────────────────────────────
        raw_date = self._collected.get("appointment_date", "")
        if raw_date:
            from datetime import date, timedelta
            today = date.today()
            d = raw_date.lower().strip()
            if d in ("tomorrow", "next day"):
                self._collected["appointment_date"] = (today + timedelta(days=1)).isoformat()
            elif d in ("day after tomorrow", "day after"):
                self._collected["appointment_date"] = (today + timedelta(days=2)).isoformat()
            # Already YYYY-MM-DD — leave as-is

    # ── Internal helpers ───────────────────────────────────────────────────────

    def _build_context_injection(self) -> str:
        """Inject current availability into the system prompt if department known."""
        lines = []

        if self._collected:
            lines.append(f"Collected so far: {json.dumps(self._collected)}")

        dept = self._collected.get("department", "")
        if dept:
            availability = self.booking.get_next_available(dept, days_ahead=5)
            if availability:
                av_lines = []
                for item in availability[:3]:
                    av_lines.append(
                        f"  {item['doctor']} | {item['date']} | "
                        + ", ".join(item["slots"][:3])
                    )
                lines.append("Available slots:\n" + "\n".join(av_lines))

        return "\n\n".join(lines)

    async def _chat(self, user_input: str) -> dict:
        """
        Single-turn async chat. Accumulates the stream and parses JSON.
        Returns a dict with at least {"speech": str, "action": str, "data": dict}.
        """
        import re
        full_raw = ""
        async for delta in self._chat_stream(user_input):
            full_raw += delta

        try:
            result = json.loads(full_raw)
            # Some models wrap the response one level deeper
            if "speech" not in result:
                for v in result.values():
                    if isinstance(v, dict) and "speech" in v:
                        result = v
                        break
            if not isinstance(result.get("speech"), str):
                raise ValueError("speech not a string")
        except Exception:
            m = re.search(r'"speech"\s*:\s*"(.*?)"', full_raw, re.DOTALL)
            speech = m.group(1) if m else (
                f"Thank you for calling {settings.hospital_name}. How can I help?"
            )
            result = {"speech": speech, "action": "none", "data": {}}

        return result

    async def _chat_stream(self, user_input: str):
        """
        Yields raw content delta strings (str) from the LLM.
        Prioritizes Gemini/Groq (free), then OpenAI, then Ollama fallback.
        """
        system = _build_system_prompt()
        ctx = self._build_context_injection()
        if ctx:
            system += f"\n\n--- LIVE CONTEXT ---\n{ctx}"

        messages = [{"role": "system", "content": system}]
        messages += self._history
        messages.append({"role": "user", "content": user_input})

        # ── Determine provider ──────────────────────────────────────────────
        client = None
        model_name = None
        base_url = None

        if settings.gemini_api_key:
            from openai import AsyncOpenAI
            client = AsyncOpenAI(
                api_key=settings.gemini_api_key,
                base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
            )
            model_name = settings.gemini_model
        elif settings.groq_api_key:
            from openai import AsyncOpenAI
            client = AsyncOpenAI(
                api_key=settings.groq_api_key,
                base_url="https://api.groq.com/openai/v1"
            )
            model_name = settings.groq_model
        elif settings.openai_api_key and settings.openai_api_key != "sk-your-key-here":
            from openai import AsyncOpenAI
            client = AsyncOpenAI(api_key=settings.openai_api_key)
            model_name = settings.openai_model

        if client:
            # ── Cloud LLM path ──────────────────────────────────────────────
            logger.info(f"[LLM] Using cloud provider for model: {model_name}")
            try:
                stream = await client.chat.completions.create(
                    model=model_name,
                    messages=messages,
                    response_format={"type": "json_object"} if "gemini" not in model_name.lower() else None, # Gemini compat note
                    temperature=0.1,
                    max_tokens=500,
                    stream=True,
                )
                async for chunk in stream:
                    delta = chunk.choices[0].delta.content
                    if delta:
                        yield delta
                return # Success
            except Exception as e:
                logger.error(f"[LLM] Cloud provider failed: {e}. Falling back to Ollama.")

        # ── Ollama fallback ──────────────────────────────────────────────────
        logger.warning("[LLM] Using local Ollama fallback")
        from ollama import AsyncClient
        async for chunk in await AsyncClient().chat(
            model=settings.ollama_model,
            messages=messages,
            format="json",
            options={"temperature": 0.1, "num_predict": 500},
            stream=True,
        ):
            delta = chunk.get("message", {}).get("content", "")
            if delta:
                yield delta

    def _execute_booking(self, result: dict) -> dict:
        info = self._collected
        try:
            apt_date = datetime.strptime(info["appointment_date"], "%Y-%m-%d").date()
            appt = self.booking.book_appointment(
                patient_name=info["patient_name"],
                patient_phone=info["patient_phone"],
                doctor_name=info["doctor_name"],
                department=info["department"],
                appointment_date=apt_date,
                appointment_time=info["appointment_time"],
                reason=info.get("reason", ""),
            )
            result["speech"] = (
                f"Your appointment is confirmed! "
                f"{appt.patient_name}, you're booked with {appt.doctor_name} "
                f"on {appt.appointment_date.strftime('%A, %B %d')} "
                f"at {appt.appointment_time}. "
                f"Your booking reference is #{appt.id}. "
                f"Is there anything else I can help you with?"
            )
            result["data"]["appointment_id"] = appt.id
        except ValueError as e:
            logger.warning(f"[Booking] Failed: {e}")
            result["speech"] = (
                f"I'm sorry, that slot is no longer available. "
                f"Let me suggest another time for you."
            )
            result["action"] = "none"
        except KeyError as e:
            logger.warning(f"[Booking] Missing field: {e}")
            result["speech"] = (
                f"I still need a few more details before I can complete the booking. "
                f"Could you please confirm {e}?"
            )
            result["action"] = "none"
        return result

    def _execute_cancellation(self, result: dict) -> dict:
        appt_id = self._collected.get("appointment_id")
        if appt_id:
            success = self.booking.cancel_appointment(int(appt_id))
            if success:
                result["speech"] = (
                    f"Your appointment #{appt_id} has been successfully cancelled. "
                    f"Is there anything else I can help you with?"
                )
            else:
                result["speech"] = (
                    f"I couldn't find a confirmed appointment with that reference. "
                    f"Could you double-check the booking ID?"
                )
        return result
